
// This file has been generated by the GUI designer. Do not modify.
namespace SoundCenSeGTK
{
	public partial class MainWindow
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.Notebook notebook1;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.ComboBox cbThreshold;
		
		private global::Gtk.ScrolledWindow scrolledwindow1;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Button btnUpdate;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView UpdateListbox;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.ScrolledWindow scrolledwindow2;
		
		private global::Gtk.VBox vboxDisabledSounds;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.VBox vbox6;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Label label12;
		
		private global::Gtk.Entry entrySoundpackPath;
		
		private global::Gtk.Button btnSoundPackPath;
		
		private global::Gtk.CheckButton cbAutoDetect;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.Label labelGamelogPath;
		
		private global::Gtk.Entry entryGamelogPath;
		
		private global::Gtk.Button btnGamelogPath;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.VBox vbox5;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Image image2;
		
		private global::Gtk.Label label10;
		
		private global::Gtk.Label label11;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Label label9;
		
		private global::Gtk.Statusbar StatusBar;
		
		private global::Gtk.ProgressBar progressbar1;
		
		private global::Gtk.Image image1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget SoundCenSeGTK.MainWindow
			this.Name = "SoundCenSeGTK.MainWindow";
			this.Title = "SoundCenSe GTK";
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("SoundCenSeGTK.Program.ico");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child SoundCenSeGTK.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 2;
			this.notebook1.ShowBorder = false;
			this.notebook1.Scrollable = true;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport ();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Notebook+NotebookChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.HeightRequest = 25;
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = "Threshold";
			this.hbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			w2.Padding = ((uint)(8));
			// Container child hbox2.Gtk.Box+BoxChild
			this.cbThreshold = global::Gtk.ComboBox.NewText ();
			this.cbThreshold.HeightRequest = 21;
			this.cbThreshold.Name = "cbThreshold";
			this.hbox2.Add (this.cbThreshold);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.cbThreshold]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox4.Add (this.hbox2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox2]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			w4.Padding = ((uint)(5));
			// Container child vbox4.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w5 = new global::Gtk.Viewport ();
			w5.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport1.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			w5.Add (this.vbox2);
			this.scrolledwindow1.Add (w5);
			this.vbox4.Add (this.scrolledwindow1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.scrolledwindow1]));
			w8.Position = 1;
			w1.Add (this.vbox4);
			this.notebook1.Add (w1);
			// Notebook tab
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = "Audio";
			this.notebook1.SetTabLabel (w1, this.label3);
			this.label3.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnUpdate = new global::Gtk.Button ();
			this.btnUpdate.Name = "btnUpdate";
			this.btnUpdate.UseUnderline = true;
			this.btnUpdate.FocusOnClick = false;
			this.btnUpdate.BorderWidth = ((uint)(10));
			this.btnUpdate.Label = "Update Soundpack";
			this.hbox1.Add (this.btnUpdate);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnUpdate]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox3.Add (this.hbox1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox1]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.UpdateListbox = new global::Gtk.TextView ();
			this.UpdateListbox.Name = "UpdateListbox";
			this.UpdateListbox.Editable = false;
			this.UpdateListbox.CursorVisible = false;
			this.UpdateListbox.AcceptsTab = false;
			this.UpdateListbox.Indent = 15;
			this.GtkScrolledWindow.Add (this.UpdateListbox);
			this.vbox3.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow]));
			w14.Position = 1;
			this.notebook1.Add (this.vbox3);
			global::Gtk.Notebook.NotebookChild w15 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vbox3]));
			w15.Position = 1;
			// Notebook tab
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = "Update";
			this.notebook1.SetTabLabel (this.vbox3, this.label5);
			this.label5.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.scrolledwindow2 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow2.CanFocus = true;
			this.scrolledwindow2.Name = "scrolledwindow2";
			// Container child scrolledwindow2.Gtk.Container+ContainerChild
			global::Gtk.Viewport w16 = new global::Gtk.Viewport ();
			w16.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport2.Gtk.Container+ContainerChild
			this.vboxDisabledSounds = new global::Gtk.VBox ();
			this.vboxDisabledSounds.Name = "vboxDisabledSounds";
			this.vboxDisabledSounds.Spacing = 6;
			this.vboxDisabledSounds.BorderWidth = ((uint)(6));
			w16.Add (this.vboxDisabledSounds);
			this.scrolledwindow2.Add (w16);
			this.notebook1.Add (this.scrolledwindow2);
			global::Gtk.Notebook.NotebookChild w19 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.scrolledwindow2]));
			w19.Position = 2;
			// Notebook tab
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = "Disabled Sounds";
			this.notebook1.SetTabLabel (this.scrolledwindow2, this.label7);
			this.label7.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			this.vbox6.BorderWidth = ((uint)(8));
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label ();
			this.label12.WidthRequest = 110;
			this.label12.Name = "label12";
			this.label12.Xalign = 0F;
			this.label12.LabelProp = "Soundpack path";
			this.hbox4.Add (this.label12);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label12]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.entrySoundpackPath = new global::Gtk.Entry ();
			this.entrySoundpackPath.Sensitive = false;
			this.entrySoundpackPath.Name = "entrySoundpackPath";
			this.entrySoundpackPath.IsEditable = false;
			this.entrySoundpackPath.InvisibleChar = '●';
			this.hbox4.Add (this.entrySoundpackPath);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.entrySoundpackPath]));
			w21.Position = 1;
			// Container child hbox4.Gtk.Box+BoxChild
			this.btnSoundPackPath = new global::Gtk.Button ();
			this.btnSoundPackPath.Name = "btnSoundPackPath";
			this.btnSoundPackPath.UseUnderline = true;
			this.btnSoundPackPath.FocusOnClick = false;
			this.btnSoundPackPath.Label = "...";
			this.hbox4.Add (this.btnSoundPackPath);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.btnSoundPackPath]));
			w22.Position = 2;
			w22.Expand = false;
			w22.Fill = false;
			this.vbox6.Add (this.hbox4);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox4]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.cbAutoDetect = new global::Gtk.CheckButton ();
			this.cbAutoDetect.Name = "cbAutoDetect";
			this.cbAutoDetect.Label = "Autodetect Dwarf Fortress";
			this.cbAutoDetect.DrawIndicator = true;
			this.cbAutoDetect.UseUnderline = true;
			this.cbAutoDetect.FocusOnClick = false;
			this.vbox6.Add (this.cbAutoDetect);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.cbAutoDetect]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			w24.Padding = ((uint)(10));
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.labelGamelogPath = new global::Gtk.Label ();
			this.labelGamelogPath.WidthRequest = 110;
			this.labelGamelogPath.Name = "labelGamelogPath";
			this.labelGamelogPath.Xalign = 0F;
			this.labelGamelogPath.LabelProp = "Gamelog path";
			this.hbox5.Add (this.labelGamelogPath);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.labelGamelogPath]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.entryGamelogPath = new global::Gtk.Entry ();
			this.entryGamelogPath.Sensitive = false;
			this.entryGamelogPath.Name = "entryGamelogPath";
			this.entryGamelogPath.IsEditable = false;
			this.entryGamelogPath.InvisibleChar = '●';
			this.hbox5.Add (this.entryGamelogPath);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.entryGamelogPath]));
			w26.Position = 1;
			// Container child hbox5.Gtk.Box+BoxChild
			this.btnGamelogPath = new global::Gtk.Button ();
			this.btnGamelogPath.Name = "btnGamelogPath";
			this.btnGamelogPath.UseUnderline = true;
			this.btnGamelogPath.FocusOnClick = false;
			this.btnGamelogPath.Label = "...";
			this.hbox5.Add (this.btnGamelogPath);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.btnGamelogPath]));
			w27.Position = 2;
			w27.Expand = false;
			w27.Fill = false;
			this.vbox6.Add (this.hbox5);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox5]));
			w28.Position = 2;
			w28.Expand = false;
			w28.Fill = false;
			this.notebook1.Add (this.vbox6);
			global::Gtk.Notebook.NotebookChild w29 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vbox6]));
			w29.Position = 3;
			// Notebook tab
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = "Configuration";
			this.notebook1.SetTabLabel (this.vbox6, this.label8);
			this.label8.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = "<span font_size=\"large\"><span font_weight=\"bold\" face=\"Courier New\">Toady One</sp" +
			"an> and <span font_weight=\"bold\" face=\"Courier New\">ThreeToe</span> for <span fo" +
			"nt_size=\"x-large\"font-weight=\"bold\" face=\"Courier New\">Dwarf Fortress</span></sp" +
			"an>";
			this.label4.UseMarkup = true;
			this.vbox5.Add (this.label4);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.label4]));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			w30.Padding = ((uint)(20));
			// Container child vbox5.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = "<span font_size=\"large\"><span font_weight=\"bold\">ZweiStein</span> for the origina" +
			"l <span font_weight=\"bold\" font_size=\"x-large\">SoundSense</span></span>";
			this.label6.UseMarkup = true;
			this.vbox5.Add (this.label6);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.label6]));
			w31.Position = 1;
			w31.Expand = false;
			w31.Fill = false;
			w31.Padding = ((uint)(20));
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.image2 = new global::Gtk.Image ();
			this.image2.Name = "image2";
			this.image2.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SoundCenSeGTK.fmod.png");
			this.hbox3.Add (this.image2);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.image2]));
			w32.Position = 0;
			w32.Fill = false;
			w32.Padding = ((uint)(8));
			// Container child hbox3.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = "<span font_size=\"large\"><span font_weight=\"bold\">FMOD Studio</span> by Firelight " +
			"Technologies</span>";
			this.label10.UseMarkup = true;
			this.hbox3.Add (this.label10);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label10]));
			w33.Position = 1;
			w33.Fill = false;
			this.vbox5.Add (this.hbox3);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox3]));
			w34.Position = 2;
			w34.Expand = false;
			w34.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = "<span font_size=\"large\"><span font_weight=\"bold\" font_size=\"large\">jecowa</span> " +
			"for his very helpful testing on OSX</span>";
			this.label11.UseMarkup = true;
			this.vbox5.Add (this.label11);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.label11]));
			w35.Position = 3;
			w35.Expand = false;
			w35.Fill = false;
			w35.Padding = ((uint)(20));
			this.notebook1.Add (this.vbox5);
			global::Gtk.Notebook.NotebookChild w36 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vbox5]));
			w36.Position = 4;
			// Notebook tab
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = "Credits";
			this.notebook1.SetTabLabel (this.vbox5, this.label2);
			this.label2.ShowAll ();
			// Notebook tab
			global::Gtk.Label w37 = new global::Gtk.Label ();
			w37.Visible = true;
			this.notebook1.Add (w37);
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = "Debug";
			this.notebook1.SetTabLabel (w37, this.label9);
			this.label9.ShowAll ();
			this.vbox1.Add (this.notebook1);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.notebook1]));
			w38.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.StatusBar = new global::Gtk.Statusbar ();
			this.StatusBar.Name = "StatusBar";
			this.StatusBar.Spacing = 6;
			// Container child StatusBar.Gtk.Box+BoxChild
			this.progressbar1 = new global::Gtk.ProgressBar ();
			this.progressbar1.WidthRequest = 100;
			this.progressbar1.Name = "progressbar1";
			this.StatusBar.Add (this.progressbar1);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.StatusBar [this.progressbar1]));
			w39.Position = 1;
			w39.Expand = false;
			w39.Fill = false;
			// Container child StatusBar.Gtk.Box+BoxChild
			this.image1 = new global::Gtk.Image ();
			this.image1.WidthRequest = 18;
			this.image1.Name = "image1";
			this.image1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SoundCenSeGTK.SignalRed.png");
			this.StatusBar.Add (this.image1);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.StatusBar [this.image1]));
			w40.Position = 2;
			w40.Expand = false;
			w40.Fill = false;
			this.vbox1.Add (this.StatusBar);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.StatusBar]));
			w41.PackType = ((global::Gtk.PackType)(1));
			w41.Position = 1;
			w41.Expand = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 419;
			this.DefaultHeight = 626;
			this.progressbar1.Hide ();
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.cbThreshold.Changed += new global::System.EventHandler (this.ThresholdChanged);
			this.btnUpdate.Clicked += new global::System.EventHandler (this.btnUpdateClick);
			this.UpdateListbox.SizeAllocated += new global::Gtk.SizeAllocatedHandler (this.ScrollDown);
			this.btnSoundPackPath.Clicked += new global::System.EventHandler (this.btnSoundPackPathClicked);
			this.cbAutoDetect.Toggled += new global::System.EventHandler (this.AutoDetectChanged);
			this.btnGamelogPath.Clicked += new global::System.EventHandler (this.btnGamelogPathClicked);
		}
	}
}
