
// This file has been generated by the GUI designer. Do not modify.
namespace SoundCenSeGTK
{
	public partial class MainWindow
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.Notebook notebook1;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.ComboBox cbThreshold;
		
		private global::Gtk.ScrolledWindow scrolledwindow1;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Button btnUpdate;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView UpdateListbox;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.Label label9;
		
		private global::Gtk.Statusbar StatusBar;
		
		private global::Gtk.ProgressBar progressbar1;
		
		private global::Gtk.Image image1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget SoundCenSeGTK.MainWindow
			this.Name = "SoundCenSeGTK.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child SoundCenSeGTK.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			this.notebook1.ShowBorder = false;
			this.notebook1.Scrollable = true;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport ();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Notebook+NotebookChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.HeightRequest = 25;
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Threshold");
			this.hbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			w2.Padding = ((uint)(8));
			// Container child hbox2.Gtk.Box+BoxChild
			this.cbThreshold = global::Gtk.ComboBox.NewText ();
			this.cbThreshold.HeightRequest = 21;
			this.cbThreshold.Name = "cbThreshold";
			this.hbox2.Add (this.cbThreshold);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.cbThreshold]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox4.Add (this.hbox2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox2]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			w4.Padding = ((uint)(5));
			// Container child vbox4.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w5 = new global::Gtk.Viewport ();
			w5.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport1.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			w5.Add (this.vbox2);
			this.scrolledwindow1.Add (w5);
			this.vbox4.Add (this.scrolledwindow1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.scrolledwindow1]));
			w8.Position = 1;
			w1.Add (this.vbox4);
			this.notebook1.Add (w1);
			// Notebook tab
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Audio");
			this.notebook1.SetTabLabel (w1, this.label3);
			this.label3.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnUpdate = new global::Gtk.Button ();
			this.btnUpdate.Name = "btnUpdate";
			this.btnUpdate.UseUnderline = true;
			this.btnUpdate.FocusOnClick = false;
			this.btnUpdate.BorderWidth = ((uint)(10));
			this.btnUpdate.Label = global::Mono.Unix.Catalog.GetString ("Update Soundpack");
			this.hbox1.Add (this.btnUpdate);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnUpdate]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox3.Add (this.hbox1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox1]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.UpdateListbox = new global::Gtk.TextView ();
			this.UpdateListbox.Name = "UpdateListbox";
			this.UpdateListbox.Editable = false;
			this.UpdateListbox.CursorVisible = false;
			this.UpdateListbox.AcceptsTab = false;
			this.UpdateListbox.Indent = 15;
			this.GtkScrolledWindow.Add (this.UpdateListbox);
			this.vbox3.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow]));
			w14.Position = 1;
			this.notebook1.Add (this.vbox3);
			global::Gtk.Notebook.NotebookChild w15 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vbox3]));
			w15.Position = 1;
			// Notebook tab
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Update");
			this.notebook1.SetTabLabel (this.vbox3, this.label5);
			this.label5.ShowAll ();
			// Notebook tab
			global::Gtk.Label w16 = new global::Gtk.Label ();
			w16.Visible = true;
			this.notebook1.Add (w16);
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Disabled Sounds");
			this.notebook1.SetTabLabel (w16, this.label7);
			this.label7.ShowAll ();
			// Notebook tab
			global::Gtk.Label w17 = new global::Gtk.Label ();
			w17.Visible = true;
			this.notebook1.Add (w17);
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Configuration");
			this.notebook1.SetTabLabel (w17, this.label8);
			this.label8.ShowAll ();
			// Notebook tab
			global::Gtk.Label w18 = new global::Gtk.Label ();
			w18.Visible = true;
			this.notebook1.Add (w18);
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Debug");
			this.notebook1.SetTabLabel (w18, this.label9);
			this.label9.ShowAll ();
			this.vbox1.Add (this.notebook1);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.notebook1]));
			w19.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.StatusBar = new global::Gtk.Statusbar ();
			this.StatusBar.Name = "StatusBar";
			this.StatusBar.Spacing = 6;
			// Container child StatusBar.Gtk.Box+BoxChild
			this.progressbar1 = new global::Gtk.ProgressBar ();
			this.progressbar1.WidthRequest = 100;
			this.progressbar1.Name = "progressbar1";
			this.StatusBar.Add (this.progressbar1);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.StatusBar [this.progressbar1]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child StatusBar.Gtk.Box+BoxChild
			this.image1 = new global::Gtk.Image ();
			this.image1.WidthRequest = 18;
			this.image1.Name = "image1";
			this.image1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SoundCenSeGTK.SignalRed.png");
			this.StatusBar.Add (this.image1);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.StatusBar [this.image1]));
			w21.Position = 2;
			w21.Expand = false;
			w21.Fill = false;
			this.vbox1.Add (this.StatusBar);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.StatusBar]));
			w22.PackType = ((global::Gtk.PackType)(1));
			w22.Position = 1;
			w22.Expand = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 494;
			this.DefaultHeight = 771;
			this.progressbar1.Hide ();
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.cbThreshold.Changed += new global::System.EventHandler (this.ThresholdChanged);
		}
	}
}
